language: scala
script: sbt ++$TRAVIS_SCALA_VERSION "test"
after_script:
  - "sbt coveralls"
scala:
  - "2.10.4"
jdk:
  - oraclejdk8
  - openjdk8
services:
  - redis
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
# whitelist
branches:
  only:
    - master
